services:
  goshort:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: goshort
    ports:
      - "8081:80" # Frontend
    environment:
      DATABASE_URL: postgres://goshort:goshort_password@goshort_db:5432/goshort?sslmode=disable
    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres:17-bullseye
    container_name: goshort_db
    restart: always
    environment:
      POSTGRES_USER: goshort
      POSTGRES_PASSWORD: goshort_password
      POSTGRES_DB: goshort
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U goshort -d goshort"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
